In [1]:
import os
print(os.path.abspath('.'))

/Users/pango/Projs/Data_Analysis/numpy/Numpy


In [3]:
import numpy as np
array = np.array([1,2,3,4,5])
print(type(array))

<class 'numpy.ndarray'>


In [4]:
array2 = array + 1
array2

array([2, 3, 4, 5, 6])

In [5]:
array + array2

array([ 3,  5,  7,  9, 11])

In [6]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [7]:
array[0]


1

In [8]:
array[3]

4

In [10]:
array.shape

(5,)

In [11]:
tang_list = [1,2,3,4,5]
tang_list.shape #list无shape属性

AttributeError: 'list' object has no attribute 'shape'

In [12]:
np.array([[1,2,3],[4,5,6]]) #构建二维矩阵

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
import numpy as np
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [4]:
type(tang_array)

numpy.ndarray

In [5]:
tang_array.dtype

dtype('int64')

In [12]:
tang_array.itemsize

8

In [11]:
tang_array.shape

(5,)

In [14]:
tang_array.size

5

In [15]:
np.size(tang_array)

5

In [17]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

In [20]:
tang_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
tang_array[1][1]

5

In [21]:
tang_array[:, 1]

array([2, 5, 8])

In [22]:
tang_array[0, 0:2]

array([1, 2])

In [23]:
tang_array2 = tang_array
tang_array2[1][1] = 100
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [33]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mask = np.array([0,0,0,0,0,0,1,1,1,1],dtype=bool)
mask

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [36]:
tang_array[mask]

array([60, 70, 80, 90])

In [38]:
rand_array = np.random.rand(10)
rand_array

mask = rand_array > 0.5
mask

rand_array[mask]

array([0.96797252, 0.76555229, 0.8068026 , 0.75378939])

In [44]:
tang_array = np.array([1,10,3.5,'str'], dtype=np.ojbect) #bug

AttributeError: module 'numpy' has no attribute 'ojbect'

In [49]:
tang_array = np.linspace(0,10,10)
print(tang_array)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [52]:
tang_array =  np.array([[1,0,6],
                       [1,7,0],
                       [2,3,1],
                       [2,4,0]])

index = np.lexsort([-1*tang_array[:,-0], tang_array[:,2]])
index

array([3, 1, 2, 0])

In [54]:
tang_array = np.arange(10)
tang_array.shape


(10,)

In [55]:
tang_array = tang_array[np.newaxis,:]
tang_array.shape 

(1, 10)

In [ ]:
import numpy as np






